name: Updraft
main: io.github.rypofalem.updraft.UpdraftPlugin
version: 1.9.2-1.0
website: rypofalem.github.io
author: RypoFalem
description: Adds updrafts that alter a player's vertical velocity
commands:
  draft:
    description: Creates or removes updrafts
    usage: /<command> ? - list subcommands
    permission: updraft.create
permissions:
  updraft.create:
    description: create updrafts and remove updrafts
    default: op
  updraft.use:
    description: affected by updrafts
    default: true